### ISSUE TITLE
impl Positioner for char is miss in 3.0

### ISSUE THREAD

**Issue by 171230839** [Marwes/combine#125]
impl Positioner for char is miss in 3.0

**Comment by Marwes** [comment]
So things have changed a bit in 3.0. `Positioner`  https://docs.rs/combine/3.0.0-alpha.4/combine/state/trait.Positioner.html is now implemented on the position type and `char` is now taken as a type parameter.

What exactly are the problem you are running into? I can see why you ran into a problem here but I can't say what the solution is without more information!

**Comment by Marwes** [comment]
@171230839  Closing, feel free to reopen if you still have problems!
