### ISSUE TITLE
RFC: Remove the backwards compatibility re-exports

### ISSUE THREAD

**Issue by Marwes** [Marwes/combine#136]
With 3.0 I have completely overhauled the module structure of Combine. All parsers now exist under sub-modules of [parser](https://docs.rs/combine/3.0.0-beta.1/combine/parser/index.html) which should hopefully be of help when one sort of know the desired behavior of the parser but do not know what it is called or even if a parser like that exists.

So if you want to "parse something between 1 to 10 times" you can look in the `parser` module, see that [repeat](https://docs.rs/combine/3.0.0-beta.1/combine/parser/repeat/index.html) matches up with wanting to parse the same thing multiple times and then there are only a handful of parsers to browse through to find [count_min_max](https://docs.rs/combine/3.0.0-beta.1/combine/parser/repeat/fn.count_min_max.html).

In the move to this structure, I kept the following modules as re-exports to minimize breakage for anyone upgrading.

```
byte
char
combinator 
range 
regex
```

Before actually releasing 3.0 proper I am considering if I should remove these re-exports to simplify the docs and make it obvious that the `parser` module is where one finds parsers. I also worry that the `combinators` re-export might not be complete which may cause users to miss parsers.

## Alternatives

* Keep the re-exports but mark them as `#[doc(hidden)]`. Keeps docs uncluttered and minimizes breakage. Might be confusing to see code working despite pointing at modules which do not exist in docs.

* Keep the re-exports as they are now. Potentially this could be done with a deprecation warning during 3.0, but then that would stick around for a long time.

**Comment by brennie** [comment]
I believe it makes sense to remove the re-exports, especially since this is going to be a major version bump. It is better to pull the bandage off quickly, IMO.

**Comment by Marwes** [comment]
@brennie Thanks for the input.

I think I have given this enough thought now and I believe the best approach is to leave the modules in place but mark them as both hidden and deprecated. That way they are effectively removed as far as anyone reading the docs is concerned but if one happens to use one (due to upgrading from 2.x or otherwise) the deprecation message can assist in upgrading to the new structure.

Since this refactoring were done so close to 3.0 I will leave the modules in place until the next major release (if one happens) as these re-exports aren't any maintenance burden (`primitives` stays removed however as that module were to messy).

**Comment by Marwes** [comment]
Closed by #142

**Comment by Clockwork-Muse** [comment]
FYI - they show up in the intellisense in VSCode.  In some cases, this hides the actual location in favor of the re-exports.

**Comment by Marwes** [comment]
Oh, I didn't consider that. I opened an issue on the rls repo to see if maybe this behaviour could (or should) be changed on that end https://github.com/rust-lang-nursery/rls/issues/911.
