### ISSUE TITLE
Implement ChoiceParser for single-item tuple

### ISSUE THREAD

**Issue by tailhook** [Marwes/combine#140]
While the following:
```
choice((
   parser(...)
)).parse_stream(...)
```
Looks kinda counter-intutive. But tt's useful when I start writing grammar with just one rule foreseeing adding more rules later. The error is quite confusing: I start to think that something wrong with type, but adding just another option works well.

**Comment by Marwes** [comment]
Same problem occurs for single item sequences (plain tuples) as well.

Note that the example actually lacks a comma in this case to make it a tuple (it would still error for the example unfortunately).
```
choice((
   parser(...),
)).parse_stream(...)
```

**Comment by tailhook** [comment]
Great! Thanks for quick response!
