### ISSUE TITLE
Document impl trait usage 

### ISSUE THREAD

**Issue by tailhook** [Marwes/combine#161]
Hi @Marwes,

In #134 you've mentioned that `impl Trait` simplifies parsers a bit. Since it's already stable can you elaborate/add examples for it?

**Comment by Marwes** [comment]
The examples have already been updated https://github.com/Marwes/combine/tree/master/examples but it seems I missed the example at the root of the docs https://docs.rs/combine/3.3.0/combine/#examples . Is there anywhere else you were thinking of?

**Comment by tailhook** [comment]
Yes, updating example in the root of the docs would be great. Sorry, forgot to take a look at the examples dir :)

**Comment by tailhook** [comment]
PR looks awesome. Thanks!
