### ISSUE TITLE
choice and string fails

### ISSUE THREAD

**Issue by FreeMasen** [Marwes/combine#167]
when using the choice parsers, if any of the choices start with the same letter matches will fail.

```rust
fn starts_with_i<I>() -> impl Parser<Input = I, Output = String>
    where  I: Stream<Item = char>,
        I::Error: ParseError<I::Item, I::Range, I::Position>,
{
    choice((
        string("implements"),
        string("interface"),
    )).map(|m| m.to_string())
}
fn test_i() {
    let i_will_pass = starts_with_i().parse("implements").unwrap();
    let i_will_fail = starts_with_i().parse("interface").unwrap();
}
```
Maybe this is by design but it is pretty confusing. I was expecting that each entry in the `choice` function would have the same behavior as `try`.

**Comment by Marwes** [comment]
Taking a bit of a guess here but I think you have misunderstood the purpose of `try`. `try` is what you use in combination with `choice` to let a parser consume multiple characters before failing and still parsers like `choice` attempt the next alternative.

So you want to do this in the `choice` parser.

```rust
choice((
        try(string("implements")),
        try(string("interface")),
    )).map(|m| m.to_string())
```

This should be explained in the choice parser's docs, it seems that I only explained this in `Parser::or` https://docs.rs/combine/3.3.2/combine/trait.Parser.html#method.or

**Comment by FreeMasen** [comment]
Thanks for the reply!
