### ISSUE TITLE
"easier" error type that does not hold references to input so it can be bubbled up over input lifetime

### ISSUE THREAD

**Issue by jpastuszek** [Marwes/combine#178]
The `easy::Errors` type holds references to actual input when using slices as input so it has to be converted to some other 'static error (String?) to be able to return it to part of application that no longer holds input for reporting or error handling purposes.

**Comment by Marwes** [comment]
Thanks for the feedback!

The idea is that you would use [`map_range`](https://docs.rs/combine/3.3.6/combine/stream/easy/struct.Errors.html#method.map_range) and its siblings to convert the error to a static for if required. The way the error type is bound to the input currently makes it makes this rather tricky however but it might be possible to provide an alternative to `Parser::easy_parse` which does the conversion automatically.
