### ISSUE TITLE
Nested parsers with .and_then_parse

### ISSUE THREAD

**Issue by jpastuszek** [Marwes/combine#179]
I don't know about parsing theory by for making parsers more generic it would be nice to have a parser function that takes another parser that is applied over it's output only. 
It should ideally merge or nest errors in such a way that if this passed parser fails, error can tell where exactly.
Also would be nice if it played nice with `range` module parsers so one can do something like `range::recognize(foo()).and_then_parse(foo_parser())` without extra allocations.
The `foo_parser()` input would then be restricted to only output of `range::recognize(foo())` so it won't have access to data before or after what `range::recognize(foo())` matched.

This would be ideal for combinators like `between`.
I have tried to do that with `.and_then()` but after 3 hours of getting trait bounds right I ended up on missing conversion from `Range::Error::StreamError` to `Input::Error` or alike.

**Comment by Marwes** [comment]
I think this is what you are looking for https://github.com/Marwes/combine/blob/f32fe7c135b8c3104843939b7b505f8b0ea4862e/examples/async.rs#L61-L63 .

Making this simpler would be a good idea though!
