### ISSUE TITLE
How to parse files with headers that indicate structure?

### ISSUE THREAD

**Issue by nausicaea** [Marwes/combine#185]
I'm currently trying to create a parser for a format with a header and a body, whose header determines the structure of the body. The header I was able to parse just fine, but I have no idea on how to get started parsing the body. Any pointers into the right direction are greatly appreciated!

The format I'm trying to parse is the [Stanford PLY](http://paulbourke.net/dataformats/ply/) format for 3-dimensional data. I wrote a [grammar](https://github.com/nausicaea/rootspace/blob/master/src/rootspace/model_parser.py#L26-L51) once that might make things clearer. The header may specify one or more elements, of which each of them in turn has one or more scalar or vector properties. Every element definition specifies how many of that type are present in the body. Furthermore, vector properties are of the format `[length data]` within the body, so the header does not fully specify the data layout of the body.

My header parser produces the following data structure as output:
```rust
struct Header {
    format: Format,
    elements: Vec<Element>,
}

struct Format {
    format_type: FormatType,
    version: Vec<usize>,
}

struct Element {
    name: String,
    count: usize,
    properties: Vec<Property>,
}

struct Property {
    name: String,
    count_data_type: Option<DataType>,
    data_type: DataType,
}

enum DataType {
    Uint8,
    Int8,
    ..
}

enum FormatType {
    Ascii,
    BinaryBe,
    BinaryLe,
}
```

More specifically, how do I create a parser that takes the parsed header, passes each element definition to a child parser, and applies those child parsers in sequence? I thought I might use `combine::parser::choice::choice` for that purpose, but I have the feeling it doesn't really fit the bill. Instead, I would probaby need something like `all(..)`. 

Thank you for this parsing library! It's fun to use and quite well-documented!

**Comment by Marwes** [comment]
Glad to hear you like it! If you want to use the parsed result to decide what to parse next then you usually want to look at one of the following parsers https://docs.rs/combine/3.4.0/combine/trait.Parser.html#method.and_then https://docs.rs/combine/3.4.0/combine/trait.Parser.html#method.flat_map https://docs.rs/combine/3.4.0/combine/trait.Parser.html#method.then . I think you probably want `then` in this case which allows you to define an entirely new parser from your parsed header.

What is probably more difficult is how to dynamically create the parsers given the header. I guess you probably want to have

```rust
impl Header {
    fn parser(self) -> impl Parser<...>
}
impl DataType {
    fn parser(self) -> impl Parser<...>
}
// etc
```
if that makes sense?

**Comment by nausicaea** [comment]
Thanks for your fast response! Well, I might not have been clear enough about my issue in hindsight.

I already knew about the associated functions to the `Parser` trait, so I was able to at least create a parser that links the header parser and the body parser:

```rust
fn ply<'a, I>() -> impl Parser<Input = I, Output = Ply> + 'a
where
    I: RangeStream<Item = u8, Range = &'a [u8]> + 'a,
    I::Error: ParseError<I::Item, I::Range, I::Position>,
{
    header()
        .then(|h| (value(h), body(&h)))
        .map(|(h, b)| Ply { header: h, body: b })
}

fn body<'a, I>(header: &Header) -> impl Parser<_, _> {
    unimplemented!()
}
```

or as per your suggestion

```rust
fn ply<'a, I>() -> impl Parser<Input = I, Output = Ply> + 'a
where
    I: RangeStream<Item = u8, Range = &'a [u8]> + 'a,
    I::Error: ParseError<I::Item, I::Range, I::Position>,
{
    header()
        .then(|h| (value(h.clone()), h.parser()))
        .map(|(h, b)| Ply { header: h, body: b })
}

impl Header {
    fn parser(self) -> impl Parser<_, _> {
        unimplemented!()
    }
}
```
Unfortunately, given your tip with the parser functions associated with each data structure, I'm still stumped at how to to actually dynamically create the parser that applies each element data parser in sequence (either by using my `body(header: &Header)` function or your proposed `Header::parser(self)` method). I mean, that parser builder function would have to return a parser that applies each child parser in sequence, but the number of child parsers could only be determined at runtime and each child parser would need to get passed a different element. I cannot just return a `Vec` or a slice, since `Parser` is not implemented for those types. In a silly attempt to get around that, I would write the following:

```rust
impl Header {
    fn parser(self) -> impl Parser<_, _> {
        let child_parsers = self.elements
            .iter()
            .map(|e| e.parser())
            .collect::<Vec<_>>();

        // Please apply all of those parsers in sequence and only succeed if all are successful. Pretty please?
        combine::parser::choice::choice(&child_parsers)
    }
}
```

I'm sorry if I'm being overly verbose. I find it quite hard to explain.

**Comment by Marwes** [comment]
Aha, in that case there isn't a parser provided that does that directly. The easiest workaround would be this I think (untested). 

```rust
{
    let len = self.elements.len();
    let mut element_parsers = self.elements.into_iter().map(|e| e.parser())l;
    count_min_max(len, len, lazy(move || elements.next().unwrap()));
}
```

**Comment by nausicaea** [comment]
Perfect! I was missing the trick with `lazy()` and an iterator inside. I should be able to get a workable parser now. Thanks for your help!

**Comment by nausicaea** [comment]
Very cool! Thank you for following up!
