### ISSUE TITLE
Update regex to 1.0

### ISSUE THREAD

**Issue by Marwes** [Marwes/combine#188]

**Comment by Marwes** [comment]
This could be done in a non breaking manner by creating a `regex-1` crate which re-exports regex 1.0 and then add it under an optional feature in combine (in the same way as `regex` is).

**Comment by Lythenas** [comment]
I just realized I'm not sure it's even possible to depend on the same crate twice with different versions. Even if it is behind features.

**Comment by Marwes** [comment]
It is actually possible using the semver trick https://github.com/dtolnay/semver-trick which would let combine depend on both `regex` and `regex-1`. Since all uses of `regex` are just to implement a trait that trait can just be implemented for both cases without breaking.

I haven't gotten around to doing this as I didn't want to just register it, but on the other hand I don't now if rust-lang want to create and maintain one either.

**Comment by Lythenas** [comment]
Very interesting read. So if I understand correctly the regex crate either needs to publish an new 0.2 minor version which re-exports the 1.0 regex crate or they need to release a second regex1 (or regex02) crate that re-exports everything from regex 1.0 (or regex 0.2). I agree that this is probably a job for the rust library team.

**Comment by Marwes** [comment]
Closed by https://github.com/Marwes/combine/pull/203/commits/77fe362c56efa6ce20e3074388aeda33cfe91c4b
