### ISSUE TITLE
How to implement a  arithmetic like "1+1x2"=3 with combine

### ISSUE THREAD

**Issue by shaitao** [Marwes/combine#189]
I think it's better to have a tutorial or example

**Comment by Marwes** [comment]
That might be a useful tutorial to have! It is non-trivial to add though so it isn't something I can just throw together.

For the moment, you may want to look into using https://docs.rs/combine-language/3.0.1/combine_language/fn.expression_parser.html from combine-language (a crate with extras for parsing programming languages). If you would like to hand-roll something I can recommend looking into https://en.wikipedia.org/wiki/Shunting-yard_algorithm which is what `expression_parser` implements.
