### ISSUE TITLE
Request for help writing a dynamic parser (again)

### ISSUE THREAD

**Issue by nausicaea** [Marwes/combine#202]
Hei, thanks again for your library, I am still enjoying using it and it's proven very versatile so far!

However, I'm stuck writing a dynamic parser that needs to parse a scalar or vector numeric value of varying encodings into a single type and I am very grateful if you can help me clear this mess :)

That output type is something of the likes of

```rust
enum Data {
    Int8(i8),
    Uint8(u8),
    ...,
    Vfloat64(Vec<f64>),
}
```

and the source data may be either ascii-encoded, big-endian or little-endian binary. Vectors are prefixed by their length (like Pascal Strings). The numeric encoding, dimensionality (scalar vs vector) and numeric data type are known ahead of time, at runtime. My attempt at an implementation currently consists of multiple levels of match statements that each contain uses of `FnOpaque` (see below), but I'm consistently getting `match arms have incompatible types, expected one opaque type, found a different opaque type` errors, and it feels like I'm approaching this entirely the wrong way.

```rust
fn property_data<'a, I>(format: FormatType, data_type: DataType, count_data_type: Option<CountType>) -> impl Parser<Input = I, Output = Data> + 'a {
    match format {
        FormatType::Ascii => {
            if count_data_type.is_some() {
                ascii_vector(data_type)
            } else {
                ascii_scalar(data_type)
            }
        },
        ...
    }
}

fn ascii_vector<'a, I>(data_type: DataType) -> FnOpaque<I, Data> {
    opaque!(ascii_count()
        .then(|c| match data_type {
            DataType::Int8 => pavi8(c),
            ...
        })
    )
}

fn pavi8<'a, I>(count: usize) -> impl Parser<Input = I, Output = Data> {
    opaque(move |f: &mut FnMut(&mut Parser<Input = _, Output = _, PartialState = _>)| {
        f(&mut no_partial(count_min_max::<Vec<_>, _>(count, count, lex(ascii_signed_integral::<I, i8>())).map(|d| d.into())))
    })
}
```

**Comment by Marwes** [comment]
In this case, where you have so many different parsers "returned" from the same function I might actually do the opposite. Use the `opaque` parser and instead of returning a parser in each branch you feed it to the closure argument (as you do in pavi8).

**Comment by Marwes** [comment]
Wrote the above on a phone but this is the idea

```rust
fn property_data<'a, I>(format: FormatType, data_type: DataType, count_data_type: Option<CountType>) -> impl Parser<Input = I, Output = Data> + 'a {
    opaque(|f| {match format {
        FormatType::Ascii => {
            if count_data_type.is_some() {
                f(&mut no_partial(ascii_vector(data_type)))
            } else {
                f(&mut no_partial(ascii_scalar(data_type)))
            }
        },
        ...
    }
    })
}
```

**Comment by nausicaea** [comment]
Thank you for that suggestion and thanks for your quick response, again! Your approach works very well (as opposed to not at all in my case). It seems like I misunderstood the use of `opaque()`.
