### ISSUE TITLE
Compilation error when running clippy from stable

### ISSUE THREAD

**Issue by davechallis** [Marwes/combine#207]
Running [clippy](https://github.com/rust-lang-nursery/rust-clippy) from stable Rust (1.29.1) on a project that uses combine currently fails with:

```
    Checking combine v3.6.0
error[E0554]: #![feature] may not be used on the stable release channel
   --> /Users/dsc/.cargo/registry/src/github.com-1ecc6299db9ec823/combine-3.6.0/src/lib.rs:193:39
    |
193 | #![cfg_attr(feature = "cargo-clippy", feature(tool_lints))]
    |                                       ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `combine`.

To learn more, run the command again with --verbose.
````

**Comment by Marwes** [comment]
I think I just forgot to remove that attribute, I am pretty sure it isn't used for anything. Want to send a PR removing it? Should be able to make a release later tonight.

**Comment by davechallis** [comment]
Sounds good, will take a look into that when I get the chance.

A quick test after removing it raises some more issues, mostly along the lines of:
```
error[E0658]: scoped lint `clippy::too_many_arguments` is experimental (see issue #44690)
   --> src/parser/sequence.rs:84:56
    |
84  |             #[cfg_attr(feature = "cargo-clippy", allow(clippy::too_many_arguments))]
    |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
but ran out of time to test until next later.

**Comment by Marwes** [comment]
Huh, I tried `rg "clippy::"` and didn't find anything so I figured I never used that syntax... But that was on the wrong branch.
