### ISSUE TITLE
Can't find a way to get a Stream<Item=u8,Range=&[u8]> from a File

### ISSUE THREAD

**Issue by joshhansen** [Marwes/combine#233]
Some parsers (e.g. `bytes`) require that the input stream have Item=u8, Range=&[u8]. In my use case, I am attempting to parse directly from a `File::open` reader, and want a `Stream` implementation that fits the requirements of `bytes`. I'm making a stream by wrapping the file reader in a `ReadStream`, then a `State`, then a `BufferedStream`. However, it turns out that this gives Range=u8, not Range=&[u8].

This issue is my request that either this functionality be provided (if it does not exist) or that it be better documented, as I have been unable to find it.

**Comment by Marwes** [comment]
Unfortunately this is impossible. For a stream to support `Range = &[u8]` the stream must already contain a`&[u8]` or else the lifetime requirements can't work out. When using `Read` that is not the case (as can be seen by the lack of lifetime).

There are a few options.

* Use non-`RangeStream` parsers such as https://docs.rs/combine/3.6.7/combine/parser/byte/fn.bytes.html (anything not in the `range` or `regex` modules).

* Read the entire thing into memory and parse the `&[u8]`. This lets you use all `RangeStream` parsers and is generally faster if you can afford to keep the whole thing in memory.

* Opt to do streaming parsing. This is much easier to do when reading asynchronously https://github.com/mitsuhiko/redis-rs/blob/aaae86f55d1230abb790178c6b7431c26a2bb2c8/src/parser.rs#L159-L179 and https://github.com/Marwes/combine/blob/9ead1b34f4fcfe7551454dae0e78a616ec8f8cdb/examples/async.rs#L93-L143 . But it can also be done synchronously with more code (though I ought to be able to package this in combine itself if needed)
https://github.com/mitsuhiko/redis-rs/blob/aaae86f55d1230abb790178c6b7431c26a2bb2c8/src/parser.rs#L201-L266 . 
However, streaming parsing only works if your data format is possible to break up into discrete chunks as each chunk you parse needs to be kept in memory until it is completely parsed after which that memory can be freed before the next chunk.
