### ISSUE TITLE
can rust/combine maintain state?

### ISSUE THREAD

**Issue by zeroexcuses** [Marwes/combine#239]
Is there a way for rust/combine to "thread a state struct" through the parsing?

For example, suppose we are counting matching ()'s ... but I want the parser to PARSE DIFFERENTLY differently depending on how many ('s it's in. So I want some state variable, it increments on (, decrements on ).

Then, there's a parser combinator where if cnt > 5, it does one thing, but if cnt < 5, it does something else.

Thanks!

**Comment by Marwes** [comment]
> Is there a way for rust/combine to "thread a state struct" through the parsing?

Have you seen https://github.com/Marwes/combine/issues/182#issuecomment-408669486 ? It explains two ways of threading state through the parser. Using that you could extend your `(`/`)` parsers to increment/decrement a counter and then check it inside a https://docs.rs/combine/3.8.1/combine/fn.parser.html after which you can dispatch to the parser you want.

There is part of an implementation for the second solution inhttps://github.com/Marwes/combine/commit/48137f71c853f8607510dc568f6def32942599b4 which you could use. I may merge it into combine later but I'd like to add some more helpers around it first.

> Then, there's a parser combinator where if cnt > 5, it does one thing, but if cnt < 5, it does something else.

I am sure you could do something with the same approach as above. But you could also do something like `(count(5, low_count_parser), many(high_count_parser))` maybe.

**Comment by zeroexcuses** [comment]
I'm not sure if the question I meant to ask and the question you thought I asked are the same.

However, I recently realized that parsers don't have to always be:

```
fn foo_parser() -> Parser<...>
```

instead, it is perfectly valid to have:

```
fn foo_parser(s: State) -> Parser<...>
```

and thus I can "thread" whatever State as needed.


PS: On an unrelated note, I think no_partial should be mentioned more prominently in the documentation. I ran into a number of problems that were easily solved via no_partial, but it took me a while to realize such a function existed.

**Comment by Marwes** [comment]
> PS: On an unrelated note, I think no_partial should be mentioned more prominently in the documentation. I ran into a number of problems that were easily solved via no_partial, but it took me a while to realize such a function existed.

Oh? Do you have an example of where this matters? It shouldn't matter except for edge cases.
