### ISSUE TITLE
serde for SourcePosition

### ISSUE THREAD

**Issue by kazimuth** [Marwes/combine#240]
Minor issue: I'd like to use SourcePosition in a serde-serializable AST but it isn't serializable, I have to do:

```rust
impl From<SourcePosition> for Position {
    fn from(position: SourcePosition) -> Position {
        let SourcePosition { line, column } = position;
        Position { line, column }
    }
}
```

and call .into() everywhere.

I understand if you don't want to bring in the dependency though.

**Comment by Marwes** [comment]
Yeah, I think converting to your own type here is the correct solution. I could bring `serde` in as an optional dependency but given how little API that could be serialized I don't think it is worth it.

https://serde.rs/field-attrs.html#with might be useful if you don't want a separate type.
