### ISSUE TITLE
parser! macro requires other macro imports in Rust 2018

### ISSUE THREAD

**Issue by kazimuth** [Marwes/combine#241]
Currently, you have to use `combine_parse_partial, combine_parser_impl, parse_mod` as well as `parser` to use the `parser!` macro in Rust 2018. This could be fixed by prefixing these macros with `combine::` in the `parser!` macro's expansion; not sure how to do back-compat there though.

**Comment by Marwes** [comment]
I believe https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-using-local_inner_macros could be used to fix this in a backwards compatible manner. For 4.x that could removed though to simplify things.
