### ISSUE TITLE
Question: custom tokens, easy_parse, and the Display trait

### ISSUE THREAD

**Issue by sjbach** [Marwes/combine#242]
Hi,

I'm attempting to parse a grammar on a custom token type, an enum with 20 or so values. Let's call it `Tok: Clone + Display`. I have the whole stream as a slice, so the simplest thing to do would seem to be to call the provided `easy_parse` on the grammar, passing in a `&[Tok]` and relying on the various stream traits already implemented on `&[T], T: Clone`.

But that seems to be a no-go if I want to do any error reporting:

```
error[E0277]: `[Tok]` doesn't implement `std::fmt::Display`
   --> src/grammar.rs:165:63
    |
165 |         .easy_parse(tokens).map_err(|err| panic!("Error: {}", err)).unwrap();
    |                                                               ^^^ `[Tok]` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `[Tok]`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: required because of the requirements on the impl of `std::fmt::Display` for `&[Tok]`
    = note: required because of the requirements on the impl of `std::fmt::Display` for `combine::stream::easy::Errors<Tok, &[Tok],
combine::stream::PointerOffset>`
    = note: required by `std::fmt::Display::fmt`
```

As implementing `Display` on `&[Tok]` is disallowed by Rust, there's no fixing this error.

My next thought was to wrap the slice in `easy::Stream`:
```
let tokens = easy::Stream(tokens);
// ...
```

But that produces the same error about `Display`. Maybe the `stream::SliceStream` newtype instead / in addition? But browsing the source, there's no `Display` implementation on `SliceStream`. (And anyway, I don't want to rewrite the grammar in terms of `&Tok` rather than `Tok` just to appease the compiler.)

What I've finally done is define my own newtype wrapper of `&[Tok]`, deferring the various stream trait implementations to the wrapped slice, and providing an implementation of `Display` on the newtype. With all this `easy_parse` error reporting works, but it's a lot of boilerplate and it feels like I'm missing something given that I'm essentially redoing `stream::SliceStream` (poorly).

Is there a better way to use `easy_parse` on a custom token type?

Thanks!

**Comment by Marwes** [comment]
That is a rather annoying limitation but the diea is that you can use https://docs.rs/combine/3.8.1/combine/stream/easy/struct.Errors.html#method.map_range (and `map_position`, `map_token`) to transform the error type into something that implements `fmt::Display` after you have parsed it.

**Comment by sjbach** [comment]
Thanks Markus. That's good enough for me. Perhaps the existence of this question will help inform others who overlook these methods. Also, thanks for your work on this package.
