### ISSUE TITLE
Reading SourcePosition during parsing?

### ISSUE THREAD

**Issue by rtfeldman** [Marwes/combine#251]
Thanks for the lovely library!

So I'm looking to read the current `line` and `column` from [`SourcePosition`](https://marwes.github.io/combine-language/combine/stream/state/struct.SourcePosition.html) inside a `Parser`, in order to implement indentation checking without additional bookkeeping.

I thought [`position()`](https://marwes.github.io/combine-language/combine/parser/item/fn.position.html) might do the trick, since "Parser which just returns the current position in the stream" sounds like exactly what I want to do, except of course it returns `Position` and not `SourcePosition`, even if that's what it will end up being at the end of parsing.

Is there some similar alternative to `position()` that exposes `SourcePosition` during parsing?

**Comment by Marwes** [comment]
The way it works is that you need to parse a `Stream` which has `SourcePosition` as `Position`. So if you wrap your input with https://docs.rs/combine/3.8.1/combine/stream/state/struct.State.html then it will work as you want.

**Comment by rtfeldman** [comment]
Hm, I think I may be misunderstanding something! If I'm understanding right, "if you wrap your input with `State`" is referring to the input I pass to `.parse()` - so something like `my_parser.parse(State::new("blah"))`.

However, I'm basically trying to make a `Parser` with `Output = i32`, where that `i32` represents the `column` from the `SourcePosition` of whatever it parsed.

Sorry if I'm confused about what you meant, but it doesn't seem like `Parser` can know ahead of time that it will be receiving `State` as an input...or is there some way to do it that I'm not aware of? (I'm relatively new to Rust and to this library, sorry!)

Concretely, I can't think of a way to implement a function with this type - or maybe some variation that restricts it to only accept streams whose inputs are wrapped in `State` - such that it would output `column` from `SourcePosition`:

```rust
fn col<I>() -> impl Parser<Input = I, Output = i32>
where I: Stream<Item = char>,
    I::Error: ParseError<I::Item, I::Range, I::Position> ,
    I: Positioned
```

Thank you for helping with this!

**Comment by Marwes** [comment]
You just need to constrain the `Position` type to be `SourcePosition`!

```rust
fn col<I>() -> impl Parser<Input = I, Output = i32>
where I: Stream<Item = char, Position = SourcePosition>,
    I::Error: ParseError<I::Item, I::Range, I::Position> ,
    I: Positioned {
    position().map(|p| p.column)
}
```

**Comment by rtfeldman** [comment]
Ahh, that's what I was missing!

Thank you so much for your help, @Marwes!
