### ISSUE TITLE
Add new repeat parsers without containers to deal with streaming or huge input

### ISSUE THREAD

**Issue by kompass** [Marwes/combine#254]
Hello ! First I love your library, the streaming-input feature is a a must for me. Thank you.

I'm working with huge files and streams, and so I can't store everything before doing computing. I can't use the parsers *many* and *sep_by*.

I do inversion of control and dependency injection : I give to the parser a pipeline, ie a dyn trait object which do the actual work with the data as soon as possible (and free space as soon as the job is done), and a filter object which says to the parser what to keep (and give to the pipeline) and what to throw.

I'm aware of the *Parser::iter* method, but since the filter works with the position of the data (not the character position but a position in a tree), I need to share with the sub-parsers a position created dynamically. *env_parser* can't do the job neither since the env is cloned at every call, so it can't be changed dynamically and shared with the next calls.

**Comment by Marwes** [comment]
You might be able to use the `skip_*` variant of the repetition parser you need

```rust
skip_many(p.map(|i| consumer.consume(i)))
```
If `skip` does not exist you can use `()` as the container to collect into while consuming the items as they come.

You may need a `RefCell` to avoid lifetime issues with `&mut`.


Alternatively you can look at embedding the consumer and any other mutable state you need in the input like I do in https://github.com/Marwes/combine-jpeg/blob/wip/src/lib.rs . (That repo is quite complicated though)

**Comment by kompass** [comment]
It works with `()` as a container, thanks ! I use `sep_by` and there is no `skip_sep_by` yet.
