### ISSUE TITLE
sep_end_by(1) succeeds without separator

### ISSUE THREAD

**Issue by jgrund** [Marwes/combine#266]
The `separator` parser in sep_end_by appears to be optional, where I would have expected an error if it was missing. Ex:

```rust
let mut parser = combine::sep_end_by::<Vec<_>, _, _, _>(digit(), token(';'));
let result = parser.easy_parse("1");
// result is: Ok((['1',], ""))
```

**Comment by Marwes** [comment]
These are modeled on the equivalent functions in parsec so In this case the documentation is just a bit unclear https://hackage.haskell.org/package/parsec-3.1.14.0/docs/Text-Parsec.html#v:sepEndBy .

For the parser that you want you can simply use `many(digit().skip(token(';'))`
