### ISSUE TITLE
Auto-derive of Copy/Clone results in too strict requirements on input

### ISSUE THREAD

**Issue by netvl** [Marwes/combine#283]
Note that `#[derive(Copy, Clone)]` on a generic type works in a rather dumb way: it requires all type arguments of a generic type to implement `Copy` and `Clone`:

```rust
#[derive(Copy, Clone)]
struct Generic<T> { ... }

// same as
struct Generic<T> { ... }

impl<T: Copy> Copy for Generic<T> { ... }
impl<T: Clone> Clone for Generic<T> { ... }
```

This is problematic for many parsers, because they have their input as a type argument. This means that in order to use such parser with `Clone`, the input type must also be cloneable, which in some cases can't be done (e.g. if it is an iterator or a `Read`). It seems that this requirement is not actually necessary: it is not needed for input to be `Clone`, because `StreamOnce::Token` and `StreamOnce::Range` are required to be `Clone` by design, which is sufficient for most if not all use cases when cloning is needed.

A proper approach would be to implement `Copy` and `Clone` by hand, omitting the `Copy` and `Clone` bounds on type arguments, making the parser types cloneable for any kind of input.

**Comment by uzytkownik** [comment]
I run into this problem when I tried to parse expression. Due to lifetimes of the structs I cannot use `parser!` macro and if I try to WAR using closures `rustc` does not finish compilation.

**Comment by Marwes** [comment]
Rather than relying on `Copy/Clone` I recommend just creating the parser twice via a closure or factoring it out into a function

```rust
let p= || / * Some complex parser */;
(p(), p(), p()) // Use it multiple times
```
