### ISSUE TITLE
How to fail a parse when a string is matched?

### ISSUE THREAD

**Issue by FridgeSeal** [Marwes/combine#285]
Hi there,

Is there a way to cause a parsing failure when a specific parser matches something? For example, I'm interested in parsing a text format similar to RDF, where I have a subject, a predicate and an object, like so:
`_subjectName <predicateName> "literal object field" .`
e.g. `_:asdf <name> "bob" .`
but some of the data I'm getting is messy and badly behaved, and has `none` or `"none"` in the object field, and I want to fail to parse when this occurs. I had a play around with `.then` and `unexpected` but couldn't get it to work (very plausible I'm just doing it wrong).

Any tips on how I could go about doing this?

**Comment by Marwes** [comment]
You can use https://docs.rs/combine/4.0.1/combine/fn.not_followed_by.html to indicate that a parser succeeding is actually a failure.

**Comment by FridgeSeal** [comment]
Ah excellent, don't know how I missed that! Thank you for that.
