### ISSUE TITLE
Docs unclear whether `parser!` should be used on nightly rust

### ISSUE THREAD

**Issue by spencerwhite** [Marwes/combine#352]
According to [this page](https://github.com/Marwes/combine/blob/master/benches/json.rs), `parser!` isn't necessary on nightly rust since you can use `impl Parser<...>` instead. It points to [this file](https://github.com/Marwes/combine/blob/master/benches/json.rs) as an example, but [this]( https://github.com/Marwes/combine/blob/master/benches/json.rs#L167 ) line uses `parser!`.

I'm not completely opposed to macros, but it would be really nice to not have to use them.

**Comment by Marwes** [comment]
`impl Parser` can be used for most parsers regardless of whether you use stable or nightly now (the comment is outdated). However you do need to use `parser!` or `opaque!` to construct parsers which contain itself to prevent the `impl Parser` type from containing itself (which is impossible). https://github.com/Marwes/combine/blob/24be5aba070b8bd36730128e26e474fc4810d446/benches/json.rs#L165-L166

**Comment by spencerwhite** [comment]
Alright, thanks
