### ISSUE TITLE
How to parse remaining input based on part of parsed input

### ISSUE THREAD

**Issue by jivagoalves** [Marwes/combine#51]
Hi @Marwes , first of all thanks for the library! Also I apologize if that's not the appropriate place to ask for help.

I'm trying to parse an amount of chars based on a parsed length. For instance, the parser I'm trying to build should return `announce` for a input like `8:announce`. `8` is the length of the string after `:`. I tried a couple of things like parsing the length and then folding as many as the size to combine several steps of `letter()`s into one parser. I'm probably missing something obvious since I'm not an expert in Rust but would appreciate any input from your side.
```rust
fn string<I>(input: State<I>) -> ParseResult<BValue, I> where I: Stream<Item=char>                                                                    
{                                                                                                                                                     
  let length = many1(digit());                                                                                                                        
  length                                                                                                                                              
    .map(|string: str::String| {                                                                                                                      
      string.parse::<i32>().unwrap()                                                                                                                  
    })                                                                                                                                                
    .skip(char(':'))                                                                                                                                  
    .then(|decimal| {                                                                                                                                 
      (0..decimal).fold(letter().map(|l| l), move |p, _| {                                                                                            
        p.and(letter()).map(|(l1, l2)| l1 + l2 )                                                                                                      
      })                                                                                                                                              
    })                                                                                                                                                
    .parse_state(input)                                                                                                                               
}
```
Code above doesn't compile and probably doesn't make sense. However, I hope it will give you the picture of what I'm trying to accomplish.

Thanks!

**Comment by Marwes** [comment]
Asking questions here is fine, no worries.

If you are fine with using the unstable range_stream feature there is a range parser which should do what you want. It might be worth adding the equivalent parser for normal streams as well though. I think you should be able to create a parser like that using the [iter](https://marwes.github.io/combine/combine/trait.ParserExt.html#method.iter) method.

In the `then` call you should be able to write something like
```
parser(move |input| {
    let mut iter = letter().iter(input);
    let result = iter.by_ref().take(decimal).collect();
    iter.into_result(result)
})
```
If there are less than `decimal` 'letter' characters this will still succeed though so you might want to check the result after parsing.

**Comment by jivagoalves** [comment]
@Marwes , thanks for your quick reply!

I did see the unstable `range_stream` feature but wanted to rely on stable ones only. So I'm ignoring it until I have a solution for normal streams. Having said that, is there any way to combine the parsers dynamically (e.g. folding/reducing to have a combined parser)?

**Comment by Marwes** [comment]
Boxing each parser is always possible but I don't think it is a good idea in this case as you would basically need to construct a parser for every different length (and you would need one box per fold so 8 in the case above).

**Comment by jivagoalves** [comment]
I see. I guess I'll use the `range_stream` feature for now. Thanks once again for your valuable input!
