### ISSUE TITLE
sep_by(any(), char(','))

### ISSUE THREAD

**Issue by Qard** [Marwes/combine#52]
Is there an uncomplicated way to achieve a parser that does `sep_by(any(), char(','))`?

I currently have something like `sep_by(parser(other), char(','))` where `other` is a separate parser that just matches `any()`, but that blows right through every instance of `,` due to the `any()` parser.

What I want is something that works the same as sep_by, but parsing the separator takes precedence over parsing the separated values. I don't want the `other` parser to need to be aware of the context in which it is used.

**Comment by Marwes** [comment]
Not really from what I can think of, you may want to make a custom "sep_by" parser to handle that.

With the current parsers combine provides though I think you might be able to hack around it with the recently added `look_ahead` parser though. `sep_by(look_ahead(satisfy(|c| c != ',')).with(parser(other)), char(','))`. It looks a bit weird but I think it should do what you want (might be some edge case I haven't considered though).

**Comment by Marwes** [comment]
I don't believe that what you want is easily possible with combine which uses recursive descent for parsing. If your `other` parser is able to successfully consume a ',' at some point during its parsing it needs to be "aware" in some way that the sep_by parser should take precedence which is at odds with combine's model in which each parser is independent of its context of use.

**Comment by Qard** [comment]
I don't think it's necessarily at odds. The parser just needs to store and consume all tokens until it reaches the tokens that get consumed by the separator parser, then feed everything up to that point into the item parser. It's kind of cheating at LALR, but it might work okay.

**Comment by Marwes** [comment]
It might work but if you have a grammar which requires you to work around it like that it might be better to use a more powerful tool library instead ([lalrpop](https://github.com/nikomatsakis/lalrpop) comes to mind but I don't know how mature it is yet).

**Comment by Marwes** [comment]
Closing. Feel free to reopen if there is more to be said on this topic

**Comment by PSeitz** [comment]
When searching for precendence in this repo, this is the only result, but it seems the combine_language crate enables this? (https://docs.rs/combine-language/3.0.1/combine_language/struct.Assoc.html#structfield.precedence)

**Comment by Marwes** [comment]
That's a slightly different meaning of precedence but yes. If you need to parse one is expressions, combine-language supports that.
