### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by cmr** [Marwes/combine#57]
This issue was automatically generated. Feel free to close without ceremony if
you do not agree with re-licensing or if it is not possible for other reasons.
Respond to @cmr with any questions or concerns, or pop over to
`#rust-offtopic` on IRC to discuss.

You're receiving this because someone (perhaps the project maintainer)
published a crates.io package with the license as "MIT" xor "Apache-2.0" and
the repository field pointing here.

TL;DR the Rust ecosystem is largely Apache-2.0. Being available under that
license is good for interoperation. The MIT license as an add-on can be nice
for GPLv2 projects to use your code.

# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback. However, this is not the
primary motivation for me creating these issues. The Apache license also has
protections from patent trolls and an explicit contribution licensing clause.
However, the Apache license is incompatible with GPLv2. This is why Rust is
dual-licensed as MIT/Apache (the "primary" license being Apache, MIT only for
GPLv2 compat), and doing so would be wise for this project. This also makes
this crate suitable for inclusion and unrestricted sharing in the Rust
standard distribution and other projects using dual MIT/Apache, such as my
personal ulterior motive, [the Robigalia project](https://robigalia.org).

Some ask, "Does this really apply to binary redistributions? Does MIT really
require reproducing the whole thing?" I'm not a lawyer, and I can't give legal
advice, but some Google Android apps include open source attributions using
this interpretation. [Others also agree with
it](https://www.quora.com/Does-the-MIT-license-require-attribution-in-a-binary-only-distribution).
But, again, the copyright notice redistribution is not the primary motivation
for the dual-licensing. It's stronger protections to licensees and better
interoperation with the wider Rust ecosystem.

# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright, due to not being a "creative
work", e.g. a typo fix) and then add the following to your README:

```
## License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, if you have them, use the following boilerplate
(based on that used in Rust):

```
// Copyright 2016 parser-combinators Developers
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.
```

It's commonly asked whether license headers are required. I'm not comfortable
making an official recommendation either way, but the Apache license
recommends it in their appendix on how to use the license.

Be sure to add the relevant `LICENSE-{MIT,APACHE}` files. You can copy these
from the [Rust](https://github.com/rust-lang/rust) repo for a plain-text
version.

And don't forget to update the `license` metadata in your `Cargo.toml` to:

    license = "MIT OR Apache-2.0"

I'll be going through projects which agree to be relicensed and have approval
by the necessary contributors and doing this changes, so feel free to leave
the heavy lifting to me!

# Contributor checkoff

To agree to relicensing, comment with :

    I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Or, if you're a contributor, you can check the box in this repo next to your
name. My scripts will pick this exact phrase up and check your checkbox, but
I'll come through and manually review this issue later as well.

 - [x] @Marwes
 - [x] @aochagavia
 - [x] @hawkw
 - [ ] @hugoduncan
 - [ ] @iblech
 - [x] @ildarsharafutdinov
 - [ ] @jxv
 - [x] @skade

**Comment by hawkw** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Marwes** [comment]
@cmr After reading through the Apache license I don't have any objections to the contents. I do however dislike that there needs to be a header in each file. There isn't some version of Apache which does not require this redundancy?

**Comment by cmr** [comment]
@Marwes I do not believe that the license header is *required*, only that it is preserved if it exists. Having a LICENSE-APACHE file (or similar) also fulfills the requirement "as indicated by a copyright notice that is included in or attached to the work".

**Comment by cmr** [comment]
e.g., https://github.com/rust-lang/rust/pull/21481#issuecomment-71029250

**Comment by Marwes** [comment]
Re-read the part at the end and that would be how I understand it as well now. In that case dual licensing is fine by me, marking as ok.

**Comment by Marwes** [comment]
@ildarsharafutdinov  commented in the duplicate issue so I marked him here.

**Comment by skade** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option

(against my personal opinion outlined here https://github.com/skade/leveldb/issues/18, but I don't want to stand in the maintainers decisions way)

**Comment by aochagavia** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Marwes** [comment]
I guess I should mention that I wouldn't mind staying as MIT so don't feel forced to accept this in any way. The only reason I feel tempted to do this license change is that I was under the impression that MIT did not require the license included in binary distributions (I would of course appreciate attribution but I don't want to force it). Thus changing the license to allow this would be more in line with my actual intent even if it complicates things (the Apache license is 8x the size of MIT which is annoying).

@skade I agree that the argument that this increases interoperability within the rust eco-system is a bit "suspect".

**Comment by skade** [comment]
@marwes Well, you would still ask for a copy of the APL included alongside in a binary distribution. It's just that the MIT text includes the author text, so _one copy per project_ must be included.

I also don't see how that's a problem, as legalities mean that distributors have to look at every project anyways on distribution. Appending another MIT blob to the resulting licensing document doesn't seem much more work then making sure that a copy of APL suffices to fulfill the requirements.

**Comment by Marwes** [comment]
@skade Then I misunderstood again and I am much less inclined to do this change. If a license need to be included anyway I don't see how it is any more complicated to just make sure the MIT license from each library used than to make sure that at least one Apache license is included.

(It occurs to me that a cargo sub command which traverses all dependencies and generates an attribution file would make MIT and Apache an equal amount of work anyway).

**Comment by cmr** [comment]
(Note: APL in the [SPDX database](https://spdx.org/licenses/) is the Adaptive Public License. The Apache license is sometimes refered to as the ASL (Apache Software License), but this name is obsolete)

@Marwes One must already include an Apache license from using the Rust stdlib. It's true that a cargo subcommand would make this easier. It's up to you!

**Comment by skade** [comment]
@cmr Still, the _checking_ whether the current license note fulfills all distribution requirements must occur, independent of the result (either that the Apache 2.0 license already included suffices or that another MIT blob must be included).

**Comment by cmr** [comment]
Yes, definitely.

**Comment by Marwes** [comment]
I don't see enough value coming from this change so I will close this. Some good discussion came out of this though which at least made me learn a thing or two about the intricacies of both MIT and the Apache license.
