### ISSUE TITLE
first and follow sets with combine?

### ISSUE THREAD

**Issue by donhcd** [Marwes/combine#64]
Do you see any way a user could implement first and follow sets using combine? I'm not sure if it's possible to add items into the stream while in the middle of parsing that same stream, but it seems impossible.

**Comment by Marwes** [comment]
I apologize for not responding but I read this issue when I didn't have time to respond to it and then unfortunately forgot.

I am not to familiar with what first and follow set implies but I think it just comes down to inserting items into the middle of a (combine) stream? If so it is not possible with the stream implementations that exist in the library as those are all more or less iterators which can be cloned.

If it only comes down to adding items to the stream while parsing then I think it should be possible to implement a stream in sort of the same way as the [buffered stream](https://github.com/Marwes/combine/blob/382a608da2851c5cc2d3477025951e9a133732bc/src/primitives.rs#L971-L1106) does which I used to implement a [lexer](https://github.com/Marwes/gluon/blob/9fed6581a649ab9befe75ab22eed5020de4009ac/parser/src/lexer.rs) in gluon which takes a string and produces a stream of tokens instead.

**Comment by donhcd** [comment]
Okay, makes sense - thanks for the response! I'm not sure if I'll need to try implementing this soon, but I'll try to contribute back if I do work on it.
