### ISSUE TITLE
Example of higher order parser generating functions.

### ISSUE THREAD

**Issue by nejucomo** [Marwes/combine#66]
I'm having trouble implementing higher order functions that create parsers. My latest attempt looks like this:

```
pub fn keyword(kw: &'static str) -> Box<Fn(&str) -> ParseResult<(), &str>>
{
    use combine::{ParserExt, string, value};

    assert!(KEYWORDS.contains(&kw));

    Box::new(|input| {
        string(kw)
            .with(value(()))
            .parse_state(input)
    })
}
```

Later I want to compose ``keyword`` in different ways. Here's an attempted use in a unit test:

```
parser(keyword("let")).skip(eof()).parse(test_case)
```

Variations on the types I've tried include:

* dropping ``Box<…>`` from the return value of ``keyword`` - ``Sized`` is not satisfied.
* dereferencing the result of ``keyword("let")`` - ``Sized`` is not satisfied.

How can I make this work?

Note: if there's a better way to implement ``keyword`` itself, that's of secondary interest. My primary interest is to learn how to create higher order parser generators.

**Comment by nejucomo** [comment]
Ah, I used to be generic over the stream type, but elsewhere I followed an example for the ``then`` docs that had this snippet:

```
// Force input to be a &str
let _: &str = input;
```

This is with ``2.0.0-beta``.

**Comment by Marwes** [comment]
It appears that `Parser` is only implemented for `FnMut` not `Fn` which I believe is why that does not just work. That being said it is not really needed (at least in this case), an easier way of writing that would be.

```rust
pub fn keyword(kw: &'static str) -> Box<Parser<Input = &str, Output = ()>
{
    use combine::{ParserExt, string, value};

    assert!(KEYWORDS.contains(&kw));

    Box::new(string(kw)
            .with(value(())))
}
```

Just be aware that boxing incurs a runtime cost (allocation + indirection) so if you want the best performance you should avoid it as much as possible.

**Comment by nejucomo** [comment]
Thanks, this indeed fixes all type errors. This is my first use of a trait object.

**Comment by Marwes** [comment]
Happy to be of help!
