### ISSUE TITLE
API request for combining satisfy and map.

### ISSUE THREAD

**Issue by nejucomo** [Marwes/combine#67]
I need to parse any of a set of characters, then return different values depending on that character. To do this, I use ``satisfy`` and then ``map``. Simplified example:

```rust
satisfy(|c| c == 'x' || c == 'y' || c == 'z')
    .map(|c| match c { 'x' => 42, 'y' => 17, 'z' => 0 })
```

Is there an existing way to eliminate the redundancy in my code, while ensuring the parser only consumes known characters? If not, the API I'm looking for is something like:

```rust
satisfy_mapped(|c| match c { 'x' => Some(42), 'y' => Some(17), 'z' => Some(0), _ => None })
```

**Comment by Marwes** [comment]
That should definitely be in the library, I have even done the same `satisfy(..).map(..)` parser in the json parser and been annoyed by it.

The only thing to decide on is the name. Maybe `satisfy_map`? Couldn't find an equivalent function in parsec or attoparsec to borrow the name from.

I will probably add this sometime next week at the same time as I add some rather significant performance improvements as well as an better interface for byte parsing to the 2.0.0 branch.

Are you using the 2.0.0-betax branch or do you want a backport for 1.x?

**Comment by Marwes** [comment]
Feel free to submit a PR if you want it a bit quicker :). The implementation for the `satisfy` parser should be reusable for this parser as well,

**Comment by Marwes** [comment]
Added to the 2.0.0 branch, will probably release 2.0.0-beta3 sometime this weekend which should hopefully be the final beta version.
