### ISSUE TITLE
Move/copy examples to examples/

### ISSUE THREAD

**Issue by Yamakaky** [Marwes/combine#68]
It more standard, and it allows to easily run them.

**Comment by Marwes** [comment]
The reason for having them in `tests` is so that they get built and run automatically with `cargo test` but I will look into moving them to examples as you are right that they should really be there!

**Comment by Yamakaky** [comment]
Oh yeah, didn't see `test/` ^^. I was talking about the examples in the doc.

**Comment by Marwes** [comment]
Aha, well I don't know what benefit there is to copy them to `examples`. I guess they could print out they result in (what they assert on)? Otherwise running them would not do anything that `cargo test test_name` does now?

**Comment by Yamakaky** [comment]
`cargo run --example`, with a `println!` of the result, I think.

**Comment by kdy1997** [comment]
You can add to Cargo.toml to run it automatically.

Cargo guide:

cargo test runs additional checks as well. For example, it will compile any examples you’ve included and will also test the examples in your documentation. Please see the testing guide in the Rust documentation for more details.

(I'm on mobile, sorry for the link)

And assert_eq! works fine with it. Test fails when assertion in example failed

**Comment by Marwes** [comment]
@kdy1997 That is only when running the tests manually. Just running `cargo test` only builds the examples and does not run them.

I think the way to fix this properly though is to have the examples in examples/ directory and then also have separate tests which runs the example executable, feeding it input to its stdin and reading its stdout to compare with the expected result. Did that for https://github.com/gluon-lang/gluon/pull/226 (though it reads/writes to tcp stream).
