### ISSUE TITLE
Code organisation for larger parser

### ISSUE THREAD

**Issue by Yamakaky** [Marwes/combine#70]
I have a [400 lines `nom` parser](https://github.com/Yamakaky/dcpu/blob/master/src/assembler/parser/nom_parser.rs) I consider to convert to `combine` (mostly for the better error messages). How would you organize it? I like being able to cleanly separate each small parser. How can I do that with `combine`?

**Comment by Marwes** [comment]
You can look at the [json parser](https://github.com/Marwes/combine/blob/master/benches/json.rs) and [gluon](https://github.com/gluon-lang/gluon/blob/8a3e9f5efd8016c77506530ebf4c8b510100d957/parser/src/lib.rs) parser. Though if you do not need to share state between the parsers you can omit the structure passed as `&self`.

```
fn parse_ident(&self, input: I) -> ParseResult<Id, I> {
    self.parser(ParserEnv::<I, F>::parse_ident2)
        .map(|x| x.0)
        .parse_stream(input)
}
```

Basically just wrap the parser in a function with the signature for [parser](https://docs.rs/combine/2.0.0/combine/fn.parser.html) and within that function just call `parse_stream`. With some extra work do it like [integer](https://github.com/Marwes/combine/blob/master/benches/json.rs#L45-L55) in the json parser. By calling parse_lazy you tell the parser to delay emitting error messages so the `integer` wraps the `parser(integer_)` (which does not emit an error) into `parser(integer_).expected("integer")` to ensure that the error message actual displays what was expected. I can try to explain `parse_lazy` in a better way if you want but most of the time you don't need to worry about it. It should just be relevant in hot loops.

**Comment by Marwes** [comment]
This is something `impl Trait` will make much nicer eventually (and with maximum performance as well). It might be possible to add some macros to make this nicer as well.

**Comment by Yamakaky** [comment]
I see. Will there be performance difference with using local variables like in the example?
```rust
    let integer = spaces()
        //parse a string of digits into an i32
        .with(many1(digit()).map(|string: String| string.parse::<i32>().unwrap()));

    //Parse integers separated by commas, skipping whitespace
    let mut integer_list = sep_by(integer, spaces().skip(char(',')));
```

**Comment by Marwes** [comment]
Nope, there should be no difference at all.

**Comment by Yamakaky** [comment]
Cool!

**Comment by Yamakaky** [comment]
I started the implementation: https://github.com/Yamakaky/dcpu/blob/combine/src/assembler/parser/combine_parser.rs
It doesn't compile and PN and SN are dummy type declarations. Could you quickly review it?

**Comment by Marwes** [comment]
Since you take a `&str` as input you may want to consider using range (zero-copy) parsers https://docs.rs/combine/2.0.0/combine/range/index.html . Also, since you use boxed parsers you may want to be careful so you don't recreate the parser to often (harming performance). But of course always profile before optimizing. Otherwise it looks as I would expect! 👍

**Comment by Yamakaky** [comment]
I tried boxed parser since I didn't really know how to return one otherwise...

**Comment by Marwes** [comment]
Ah, sorry. The way to "return" a parser without boxing right now is to write roughly

```
fn my_parser(input: &str) -> ParseResult<&str, Output> {
    complicated_parser.parse_stream(input)
}

// Use my_parser
parser(my_parser).parse("abc");
```

That way the type is hidden by the function.

**Comment by Yamakaky** [comment]
Does your `pos_number` work with `Or`?

**Comment by Marwes** [comment]
Yep, [parser](https://docs.rs/combine/2.0.0/combine/fn.parser.html) is just a way to make a `Parser` from a function.

**Comment by Marwes** [comment]
Alternatively, with a bit more boilerplate you could write this.
```
fn pos_number() -> Expected<FnParser<fn (&str) -> ParseResult<&str, int>>> {
    parser(pos_number_).expected("positive number")
}
fn pos_number_(input: &str) -> ParseResult<&str, int> {
    raw_number().and_then(|(digits, base)| u16::from_str_radix(digits,
                                                                    base)).parse_lazy(input)
}

pos_number().parse("abc");
```

By calling `parse_lazy` over `parse_stream` it becomes slightly more efficient if `pos_number` are used in `or`. This is because the parser holds off on generating error information for as long as possible until an entire chain of `or` parsers has failed.

*Making a note to properly explain how this works somewhere in the documentation*

**Comment by Yamakaky** [comment]
Make an other note: generate `pos_number` using a macro ^^

**Comment by Marwes** [comment]
Perhaps, that would work in this case but it would not be possible to define a parser that was generic if it were a macro. Most of my own parsers are generic which is why I haven't added it.

```rust
fn pos_number<I>() -> Expected<FnParser<fn (I) -> ParseResult<I, int>>> where I : Stream<Item = char> {
    parser(pos_number_).expected("positive number")
}
fn pos_number_<I>(input: I) -> ParseResult<I, int> where I : Stream<Item = char> {
    raw_number().and_then(|(digits, base)| u16::from_str_radix(digits,
                                                                    base)).parse_lazy(input)
}
```

**Comment by Marwes** [comment]
Had a thought, as long as the parsers are not incredibly complex or mutually recursive an easy way to get re-usability could be to use macros which produce parsers.

```
macro_rules! pos_number {
    () => { raw_number().and_then(|(digits, base)| u16::from_str_radix(digits, base)) }
}

pos_number!().parse_*(input)
```

**Comment by Yamakaky** [comment]
why not ^^
