### ISSUE TITLE
uncons_while should take an item reference

### ISSUE THREAD

**Issue by ncalexan** [Marwes/combine#75]
I'd like to understand some of the API decisions the library makes. Like in #74 , my motivating use case is to parse a token stream (not a character stream), and my tokens do not implement `Copy` because they include `String` data, like:
```
struct Token {
    Keyword(String),
    ...
}
```
While implementing `RangeStream` for a newtype wrapping `&'a [Token]` (like `SliceStream` but with item type `Token` rather item type `&'a Token`), I've run into the following question.  Why does `uncons_while` take an `FnMut(Item)` rather than `FnMut(&Item)` at https://github.com/Marwes/combine/blob/master/src/primitives.rs#L562?

In general, the Rust-y pattern seems to be that predicate filters take references to the elements in their containing collection -- but I'm not an experienced Rust user so I'm probably missing something.  Any guidance appreciated.

**Comment by Marwes** [comment]
Summed together both answers in https://github.com/Marwes/combine/issues/74#issuecomment-270799586 since it is more or less the same reason.

**Comment by ncalexan** [comment]
> Summed together both answers in #74 (comment) since it is more or less the same reason.

Thanks for your very useful answer.  I think this can just be closed with a link to https://github.com/Marwes/combine/pull/44#issuecomment-135524413 which justifies the ergonomics and a link to https://github.com/Marwes/combine/issues/74#issuecomment-270799586 which justifies the performance assumptions.
