### ISSUE TITLE
Copy/paste errors in docs of count and none_of combinators

### ISSUE THREAD

**Issue by jgallagher** [Marwes/combine#82]
`count`, `none_of`, and `one_of` all have the same document description:

> Extract one token and succeeds if it is part of tokens.

which I assume is correct for `one_of` but not the other two. :) Additionally, the docs for `count` give an example of `none_of`:

```rust
let result = many(none_of("abc".chars()))
    .parse("edc");
assert_eq!(result, Ok((String::from("ed"), "c")));
```

**Comment by Marwes** [comment]
Fixed in 97e3a244c838133e408bce6176830a803fce362e, thanks for reporting!
