### ISSUE TITLE
An example with stdin

### ISSUE THREAD

**Issue by tikue** [Marwes/combine#84]
What's the right way to parse input from stdin? I'm hitting lifetime issues when reading into a `String` and passing that to `parse`.

**Comment by Marwes** [comment]
You can use [from_read](https://docs.rs/combine/2.2.2/combine/primitives/fn.from_read.html) to parse from something implementing `std::io::Read` (such as stdin). It will probably be a bit slower than reading it into a string first though.

**Comment by Marwes** [comment]
Both the `ini` and the `date` examples display how to parse from `stdin` (or anything else that implements `Read`). Closing.
