### ISSUE TITLE
Comparison to chomp

### ISSUE THREAD

**Issue by DemiMarie** [Marwes/combine#89]
[Chomp](https://github.com/m4rw3r/chomp) is another parser combinator library for Rust.  It aims at being as fast or faster than parsers hand-written in C.

How does Chomp compare to Combine?

**Comment by Marwes** [comment]
Its current implementation relies a lot on macros which has the usual conveniences of convenient syntax at the cost of generality and needing to learn the macro's syntax. There has been some efforts in chomp to move away from the macro based solution I think which more or less resulted in the same trait based approach as in combine (with an almost identical Parser trait).

Performance should be roughly the same, chomp (and nom) can be slightly faster (a couple of %) as combine makes an effort to construct good errors.
