### ISSUE TITLE
Documentation link in crates.io is broken

### ISSUE THREAD

**Issue by pmatos** [Marwes/combine#97]
https://crates.io/crates/parser-combinators links to https://marwes.github.io/parser-combinators/parser_combinators/index.html which doesn't exist.

**Comment by Marwes** [comment]
I suppose I could change it to point to https://docs.rs/parser-combinators/0.7.0/parser_combinators/ but there is practically no reason to be using such an old version of the library. I really recommend using at least combine-1.0.0 at least. https://crates.io/crates/combine

**Comment by Marwes** [comment]
Oops, actually the documentation link on https://crates.io/crates/combine is actually wrong as well, it should point to https://docs.rs/combine/2.3.1/combine/

**Comment by pmatos** [comment]
Argh, I didn't notice `parser_combinators` was forwarding me to `combine`. Thanks for your time. Maybe `parser_combinators` could be removed from crates.io?

**Comment by Marwes** [comment]
Can't really remove it since there might be people that still need (there are a download of it every now and then). Could maybe add DEPRECEATED in the description so it is more eye catching.

**Comment by pmatos** [comment]
Sounds like a good idea. If possible, for new users, some explicit text pointing them to use `combine` instead.

**Comment by Marwes** [comment]
Fixed with 60bfe8e0392fc18994eb9bd0fe1a8536d683b981 and c93b81ad4fafffe1011100231323aa6f899b7bbb

**Comment by pmatos** [comment]
@Marwes Thanks.
