### ISSUE TITLE
`any()` should not produce ConsumedErr

### ISSUE THREAD

**Issue by yubrot** [Marwes/combine#99]
Maybe it's a simple clerical error. `any()` should behave the same way as `satisfy(|_| true)`.
https://github.com/Marwes/combine/blob/75209e894f084f2bd0a0742b65c08bb7598f090b/src/combinator.rs#L48
https://github.com/Marwes/combine/blob/75209e894f084f2bd0a0742b65c08bb7598f090b/src/combinator.rs#L94

**Comment by Marwes** [comment]
Will be fixed with #100, this is a rare bug in practice luckily. Thanks for reporting!
